---
- hosts: worker
  become: true
  vars:
    app_dir: /opt/todo-app
    app_image: todo-app:latest
    container_name: todo-app
    network_name: todo_network
    host_port: 1080

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files
      copy:
        src: "{{ lookup('env', 'WORKSPACE_ARCHIVE') }}"
        dest: "{{ app_dir }}/project.tar.gz"

    - name: Extract project files
      unarchive:
        src: "{{ app_dir }}/project.tar.gz"
        dest: "{{ app_dir }}"
        remote_src: yes

    - name: Remove old Docker containers and images
      block:
        - name: Stop and remove existing containers
          docker_container:
            name: "{{ container_name }}"
            state: absent
          ignore_errors: yes

        - name: Remove old images
          docker_image:
            name: "{{ app_image }}"
            state: absent
            force_absent: yes
          ignore_errors: yes

    - name: Build Docker image
      docker_image:
        name: "{{ app_image }}"
        build:
          path: "{{ app_dir }}"
          dockerfile: Dockerfile
        source: build
        force_source: true

    - name: Ensure Docker network exists
      docker_network:
        name: "{{ network_name }}"
        state: present

    - name: Deploy application container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ app_image }}"
        state: started
        restart_policy: unless-stopped
        networks:
          - name: "{{ network_name }}"
        ports:
          - "{{ host_port }}:80"
        env:
          NODE_ENV: production

    - name: Clean up build artifacts
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ app_dir }}/project.tar.gz"
      ignore_errors: yes

    - name: Verify deployment
      uri:
        url: "http://localhost:{{ host_port }}"
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 6
      delay: 10
      ignore_errors: yes

    - name: Display deployment status
      debug:
        msg: "Application is now accessible at http://{{ inventory_hostname }}:{{ host_port }}"
      when: health_check.status is defined and health_check.status == 200
